"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.undefined = exports.string = exports.number = exports.null = exports.literal = exports.boolean = void 0;
const BooleanType_1 = __importDefault(require("./types/primitives/BooleanType"));
const LiteralType_1 = __importDefault(require("./types/primitives/LiteralType"));
const NullType_1 = __importDefault(require("./types/primitives/NullType"));
const NumberType_1 = __importDefault(require("./types/primitives/NumberType"));
const StringType_1 = __importDefault(require("./types/primitives/StringType"));
const UndefinedType_1 = __importDefault(require("./types/primitives/UndefinedType"));
const boolean = new BooleanType_1.default();
exports.boolean = boolean;
const literal = (of) => new LiteralType_1.default(of);
exports.literal = literal;
const nullType = new NullType_1.default();
exports.null = nullType;
const number = new NumberType_1.default();
exports.number = number;
const string = (options = {}) => new StringType_1.default(options);
exports.string = string;
const undefined = new UndefinedType_1.default();
exports.undefined = undefined;
